

[build]
  command = "npm run build"
  publish = "dist"

# Catch-all so deep links serve index.html
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-prerender-spa"
  [plugins.inputs]
    source = "dist"
    minifyHTMLOpts = true
    # Add timeout and debugging options
    renderAfterTime = 1000
    renderAfterElementExists = "body"
    timeout = 300000
    # 5 minute timeout instead of default
    crawlLinksFromMarkup = false
    # Disable automatic link crawling to prevent infinite loops

