
[build]
  command = "npm run build"
  publish = "dist"

# Catch-all so deep links serve index.html if prerender misses anything
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-prerender-spa"
  [plugins.inputs]
    source = "dist"
    minifyHTMLOpts = true
    # Explicit routes to ensure all pages get prerendered
    routes = [
      "/",
      "/presentation-generator",
      "/viral-post-generator", 
      "/prompt-genius",
      "/meme-generator",
      "/smart-reply",
      "/lead-genie",
      "/document-genie",
      "/contract-scanner"
    ]
