// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdtiivkvirtuwzbqctgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkdGlpdmt2aXJ0dXd6YnFjdGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTM5OTQsImV4cCI6MjA2MTQ4OTk5NH0.jf7cP81STdTYxv2emns5lY1xFmZaQ00XR3VTmm5bqeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);